#!/bin/bash
set -eu

GCC_VERSION_=$(docker run -t --rm ${IMAGE_NAME} arm-none-eabi-gcc --version | grep "arm-none-eabi-gcc")
GCC_VERSION=$(echo ${GCC_VERSION_} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+')

echo $GCC_VERSION
